/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author galla
 */
public class CartonPanel extends javax.swing.JPanel {

    /**
     * Creates new form CartonPanel
     */
    public CartonPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDestacarTodo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_r0c0 = new javax.swing.JTextField();
        txt_r0c1 = new javax.swing.JTextField();
        txt_r0c2 = new javax.swing.JTextField();
        txt_r0c3 = new javax.swing.JTextField();
        txt_r0c4 = new javax.swing.JTextField();
        txt_r1c0 = new javax.swing.JTextField();
        txt_r1c1 = new javax.swing.JTextField();
        txt_r1c2 = new javax.swing.JTextField();
        txt_r1c3 = new javax.swing.JTextField();
        txt_r1c4 = new javax.swing.JTextField();
        txt_r2c0 = new javax.swing.JTextField();
        txt_r2c1 = new javax.swing.JTextField();
        txt_r2c2 = new javax.swing.JTextField();
        txt_r2c3 = new javax.swing.JTextField();
        txt_r2c4 = new javax.swing.JTextField();
        txt_r3c0 = new javax.swing.JTextField();
        txt_r3c1 = new javax.swing.JTextField();
        txt_r3c2 = new javax.swing.JTextField();
        txt_r3c3 = new javax.swing.JTextField();
        txt_r3c4 = new javax.swing.JTextField();
        txt_r4c0 = new javax.swing.JTextField();
        txt_r4c1 = new javax.swing.JTextField();
        txt_r4c2 = new javax.swing.JTextField();
        txt_r4c3 = new javax.swing.JTextField();
        txt_r4c4 = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(135, 6, 6));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImgsTablero/bingo titulo.png"))); // NOI18N
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(135, 6, 6));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnDestacarTodo.setBackground(new java.awt.Color(255, 211, 57));
        btnDestacarTodo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDestacarTodo.setText("Destacar Todo");
        btnDestacarTodo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(btnDestacarTodo);

        jLabel2.setBackground(new java.awt.Color(242, 211, 57));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Listo");
        jPanel2.add(jLabel2);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(135, 6, 6));
        jPanel3.setLayout(new java.awt.GridLayout(6, 5, 5, 6));

        txt_r0c0.setBackground(new java.awt.Color(255, 211, 57));
        txt_r0c0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r0c0.setText("jTextField1");
        txt_r0c0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r0c0);

        txt_r0c1.setBackground(new java.awt.Color(255, 211, 57));
        txt_r0c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r0c1.setText("jTextField2");
        txt_r0c1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r0c1);

        txt_r0c2.setBackground(new java.awt.Color(255, 211, 57));
        txt_r0c2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r0c2.setText("jTextField3");
        txt_r0c2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r0c2);

        txt_r0c3.setBackground(new java.awt.Color(255, 211, 57));
        txt_r0c3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r0c3.setText("jTextField4");
        txt_r0c3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r0c3);

        txt_r0c4.setBackground(new java.awt.Color(255, 211, 57));
        txt_r0c4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r0c4.setText("jTextField5");
        txt_r0c4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r0c4);

        txt_r1c0.setBackground(new java.awt.Color(255, 211, 57));
        txt_r1c0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r1c0.setText("jTextField6");
        txt_r1c0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r1c0);

        txt_r1c1.setBackground(new java.awt.Color(255, 211, 57));
        txt_r1c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r1c1.setText("jTextField7");
        txt_r1c1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r1c1);

        txt_r1c2.setBackground(new java.awt.Color(255, 211, 57));
        txt_r1c2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r1c2.setText("jTextField8");
        txt_r1c2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r1c2);

        txt_r1c3.setBackground(new java.awt.Color(255, 211, 57));
        txt_r1c3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r1c3.setText("jTextField9");
        txt_r1c3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r1c3);

        txt_r1c4.setBackground(new java.awt.Color(255, 211, 57));
        txt_r1c4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r1c4.setText("jTextField10");
        txt_r1c4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r1c4);

        txt_r2c0.setBackground(new java.awt.Color(255, 211, 57));
        txt_r2c0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r2c0.setText("jTextField13");
        txt_r2c0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r2c0);

        txt_r2c1.setBackground(new java.awt.Color(255, 211, 57));
        txt_r2c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r2c1.setText("jTextField22");
        txt_r2c1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r2c1);

        txt_r2c2.setBackground(new java.awt.Color(204, 204, 204));
        txt_r2c2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_r2c2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r2c2.setText("FREE");
        txt_r2c2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_r2c2.setEnabled(false);
        jPanel3.add(txt_r2c2);

        txt_r2c3.setBackground(new java.awt.Color(255, 211, 57));
        txt_r2c3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r2c3.setText("jTextField12");
        txt_r2c3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r2c3);

        txt_r2c4.setBackground(new java.awt.Color(255, 211, 57));
        txt_r2c4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r2c4.setText("jTextField14");
        txt_r2c4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r2c4);

        txt_r3c0.setBackground(new java.awt.Color(255, 211, 57));
        txt_r3c0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r3c0.setText("jTextField19");
        txt_r3c0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r3c0);

        txt_r3c1.setBackground(new java.awt.Color(255, 211, 57));
        txt_r3c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r3c1.setText("jTextField21");
        txt_r3c1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r3c1);

        txt_r3c2.setBackground(new java.awt.Color(255, 211, 57));
        txt_r3c2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r3c2.setText("jTextField18");
        txt_r3c2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r3c2);

        txt_r3c3.setBackground(new java.awt.Color(255, 211, 57));
        txt_r3c3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r3c3.setText("jTextField15");
        txt_r3c3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r3c3);

        txt_r3c4.setBackground(new java.awt.Color(255, 211, 57));
        txt_r3c4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r3c4.setText("jTextField25");
        txt_r3c4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r3c4);

        txt_r4c0.setBackground(new java.awt.Color(255, 211, 57));
        txt_r4c0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r4c0.setText("jTextField17");
        txt_r4c0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r4c0);

        txt_r4c1.setBackground(new java.awt.Color(255, 211, 57));
        txt_r4c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r4c1.setText("jTextField16");
        txt_r4c1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r4c1);

        txt_r4c2.setBackground(new java.awt.Color(255, 211, 57));
        txt_r4c2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r4c2.setText("jTextField20");
        txt_r4c2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r4c2);

        txt_r4c3.setBackground(new java.awt.Color(255, 211, 57));
        txt_r4c3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r4c3.setText("jTextField23");
        txt_r4c3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r4c3);

        txt_r4c4.setBackground(new java.awt.Color(255, 211, 57));
        txt_r4c4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_r4c4.setText("jTextField24");
        txt_r4c4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_r4c4);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDestacarTodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_r0c0;
    private javax.swing.JTextField txt_r0c1;
    private javax.swing.JTextField txt_r0c2;
    private javax.swing.JTextField txt_r0c3;
    private javax.swing.JTextField txt_r0c4;
    private javax.swing.JTextField txt_r1c0;
    private javax.swing.JTextField txt_r1c1;
    private javax.swing.JTextField txt_r1c2;
    private javax.swing.JTextField txt_r1c3;
    private javax.swing.JTextField txt_r1c4;
    private javax.swing.JTextField txt_r2c0;
    private javax.swing.JTextField txt_r2c1;
    private javax.swing.JTextField txt_r2c2;
    private javax.swing.JTextField txt_r2c3;
    private javax.swing.JTextField txt_r2c4;
    private javax.swing.JTextField txt_r3c0;
    private javax.swing.JTextField txt_r3c1;
    private javax.swing.JTextField txt_r3c2;
    private javax.swing.JTextField txt_r3c3;
    private javax.swing.JTextField txt_r3c4;
    private javax.swing.JTextField txt_r4c0;
    private javax.swing.JTextField txt_r4c1;
    private javax.swing.JTextField txt_r4c2;
    private javax.swing.JTextField txt_r4c3;
    private javax.swing.JTextField txt_r4c4;
    // End of variables declaration//GEN-END:variables
}
