/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author galla
 */
public class CartonesGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form CartonesGUI
     */
    public CartonesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        cmbModoCreacion = new javax.swing.JComboBox<>();
        tabsCartones = new javax.swing.JTabbedPane();

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnNuevo.setText("Nuevo Carton");
        jPanel1.add(btnNuevo);

        btnEliminar.setText("Eliminar");
        jPanel1.add(btnEliminar);

        btnLimpiar.setText("Limpiar Marcas");
        jPanel1.add(btnLimpiar);

        lblTotal.setText("jLabel1");
        jPanel1.add(lblTotal);

        cmbModoCreacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbModoCreacion);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tabsCartones.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tabsCartones, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbModoCreacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTabbedPane tabsCartones;
    // End of variables declaration//GEN-END:variables
}
