/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CartonController;
import java.awt.TextField;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author huete
 */
public class GUICrearCarton extends javax.swing.JInternalFrame {

    // SINGLETON
    private static GUICrearCarton instancia;

    // HashMap 
    private HashMap<Integer, TextField> mapaCampos;

    public GUICrearCarton() {
        initComponents();
        inicializarTextFields();
    }

    public static GUICrearCarton getInstancia() {
        if (instancia == null) {
            instancia = new GUICrearCarton();
        }
        return instancia;
    }

    public HashMap<Integer, TextField> getMapaCampos() {
        return mapaCampos;
    }
    
    public void limpiarCampos() {
    for (TextField campo : mapaCampos.values()) {
        if (!campo.equals(txtfree)) { // No limpiar el campo FREE
            campo.setText("");
        }
    }
}

    private void inicializarTextFields() {
        mapaCampos = new HashMap<>();
        
        TextField[] campos = {
            txt1, txt2, txt3, txt4, txt5,
            txt6, txt7, txt8, txt9, txt10,
            txt11, txt12, txtfree, txt14, txt15,
            txt16, txt17, txt18, txt19, txt20,
            txt21, txt22, txt23, txt24, txt25
        };

        // Llenar HashMap empezando desde 1
        for (int i = 0; i < campos.length; i++) {
            mapaCampos.put(i + 1, campos[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAgregarCarton = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        txt1 = new java.awt.TextField();
        txt2 = new java.awt.TextField();
        txt3 = new java.awt.TextField();
        txt4 = new java.awt.TextField();
        txt5 = new java.awt.TextField();
        txt6 = new java.awt.TextField();
        txt7 = new java.awt.TextField();
        txt8 = new java.awt.TextField();
        txt9 = new java.awt.TextField();
        txt10 = new java.awt.TextField();
        txt11 = new java.awt.TextField();
        txt12 = new java.awt.TextField();
        txtfree = new java.awt.TextField();
        txt14 = new java.awt.TextField();
        txt15 = new java.awt.TextField();
        txt16 = new java.awt.TextField();
        txt17 = new java.awt.TextField();
        txt18 = new java.awt.TextField();
        txt19 = new java.awt.TextField();
        txt20 = new java.awt.TextField();
        txt21 = new java.awt.TextField();
        txt22 = new java.awt.TextField();
        txt23 = new java.awt.TextField();
        txt24 = new java.awt.TextField();
        txt25 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 0, 0));
        setPreferredSize(new java.awt.Dimension(504, 470));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonAgregarCarton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        buttonAgregarCarton.setLabel("Agregar");
        buttonAgregarCarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarCartonActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAgregarCarton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        jPanel2.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 67, 40));

        txt2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 67, 40));

        txt3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 67, 40));

        txt4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 67, 40));

        txt5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 67, 40));

        txt6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt6ActionPerformed(evt);
            }
        });
        jPanel2.add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 10, 67, 40));

        txt7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 60, 67, 40));

        txt8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 110, 67, 40));

        txt9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 160, 67, 40));

        txt10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 210, 67, 40));

        txt11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt11, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 10, 67, 40));

        txt12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt12, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 60, 67, 40));

        txtfree.setEditable(false);
        txtfree.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtfree.setText("FREE");
        txtfree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfreeActionPerformed(evt);
            }
        });
        jPanel2.add(txtfree, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 110, 67, 40));

        txt14.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt14ActionPerformed(evt);
            }
        });
        jPanel2.add(txt14, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 160, 67, 40));

        txt15.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt15, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 210, 67, 40));

        txt16.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt16, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 10, 67, 40));

        txt17.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt17, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 60, 67, 40));

        txt18.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt18, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 110, 67, 40));

        txt19.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt19, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 160, 67, 40));

        txt20.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt20, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 210, 67, 40));

        txt21.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt21, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 10, 69, 40));

        txt22.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt22, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 60, 67, 40));

        txt23.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt23, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 110, 67, 40));

        txt24.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt24, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 160, 67, 40));

        txt25.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.add(txt25, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 210, 67, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImgsTablero/bingo titulo.png"))); // NOI18N
        jLabel1.setText("jLabel3");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 492, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt6ActionPerformed

    private void txtfreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfreeActionPerformed

    private void txt14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt14ActionPerformed

    private void buttonAgregarCartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarCartonActionPerformed
            try {
        // Obtener los números de los campos de texto
        String[][] numerosIngresados = new String[5][5];
        
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                int posicion = i * 5 + j + 1;
                TextField campo = mapaCampos.get(posicion);
                
                if (i == 2 && j == 2) {
                    numerosIngresados[j][i] = "0"; // Casilla FREE
                } else {
                    numerosIngresados[j][i] = campo.getText().trim();
                }
            }
        }
        
        // Llamar al controlador para agregar el cartón manual
        CartonController controlador = CartonController.getInstancia();
        String resultado = controlador.agregarCartonManual(numerosIngresados);
        
        if (resultado.contains("éxito")) {
            JOptionPane.showMessageDialog(this, resultado, "Cartón Agregado", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, resultado, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al procesar el cartón: " + ex.getMessage(), 
                                    "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_buttonAgregarCartonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonAgregarCarton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.TextField txt1;
    private java.awt.TextField txt10;
    private java.awt.TextField txt11;
    private java.awt.TextField txt12;
    private java.awt.TextField txt14;
    private java.awt.TextField txt15;
    private java.awt.TextField txt16;
    private java.awt.TextField txt17;
    private java.awt.TextField txt18;
    private java.awt.TextField txt19;
    private java.awt.TextField txt2;
    private java.awt.TextField txt20;
    private java.awt.TextField txt21;
    private java.awt.TextField txt22;
    private java.awt.TextField txt23;
    private java.awt.TextField txt24;
    private java.awt.TextField txt25;
    private java.awt.TextField txt3;
    private java.awt.TextField txt4;
    private java.awt.TextField txt5;
    private java.awt.TextField txt6;
    private java.awt.TextField txt7;
    private java.awt.TextField txt8;
    private java.awt.TextField txt9;
    private java.awt.TextField txtfree;
    // End of variables declaration//GEN-END:variables

}
