/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import java.util.HashMap;
import javax.swing.JTextField;

/**
 *
 * @author Dennis
 */
public class TableroGUI extends javax.swing.JInternalFrame {

    //ATRIBUTOS
    private static TableroGUI instancia;
    private HashMap<Integer, JTextField> numerosTxts;
    
    public TableroGUI() {
        initComponents();
        inicializarNumerostTxts();
    }

    public static TableroGUI getInstancia() {
    //SINGLETON
        if (instancia == null) {
            instancia = new TableroGUI();
        }
        return instancia;
    }

    public HashMap<Integer, JTextField> getNumerosTxts() {
        return numerosTxts;
    }

    private void inicializarNumerostTxts() {
        numerosTxts = new HashMap<>();
        //Para manipular todos los botones en un hashmap
        JTextField[] botones = {
            txt1, txt2, txt3, txt4, txt5, txt6, txt7, txt8, txt9, txt10,
            txt11, txt12, txt13, txt14, txt15, txt16, txt17, txt18, txt19, txt20,
            txt21, txt22, txt23, txt24, txt25, txt26, txt27, txt28, txt29, txt30,
            txt31, txt32, txt33, txt34, txt35, txt36, txt37, txt38, txt39, txt40,
            txt41, txt42, txt43, txt44, txt45, txt46, txt47, txt48, txt49, txt50,
            txt51, txt52, txt53, txt54, txt55, txt56, txt57, txt58, txt59, txt60,
            txt61, txt62, txt63, txt64, txt65, txt66, txt67, txt68, txt69, txt70,
            txt71, txt72, txt73, txt74, txt75
        };
        
        for (int i = 0; i < botones.length; i++) {
            numerosTxts.put(i + 1, botones[i]);
        }
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        txt11 = new javax.swing.JTextField();
        txt12 = new javax.swing.JTextField();
        txt13 = new javax.swing.JTextField();
        txt14 = new javax.swing.JTextField();
        txt15 = new javax.swing.JTextField();
        txt16 = new javax.swing.JTextField();
        txt17 = new javax.swing.JTextField();
        txt18 = new javax.swing.JTextField();
        txt19 = new javax.swing.JTextField();
        txt20 = new javax.swing.JTextField();
        txt21 = new javax.swing.JTextField();
        txt22 = new javax.swing.JTextField();
        txt23 = new javax.swing.JTextField();
        txt24 = new javax.swing.JTextField();
        txt25 = new javax.swing.JTextField();
        txt26 = new javax.swing.JTextField();
        txt27 = new javax.swing.JTextField();
        txt28 = new javax.swing.JTextField();
        txt29 = new javax.swing.JTextField();
        txt30 = new javax.swing.JTextField();
        txt31 = new javax.swing.JTextField();
        txt32 = new javax.swing.JTextField();
        txt33 = new javax.swing.JTextField();
        txt34 = new javax.swing.JTextField();
        txt35 = new javax.swing.JTextField();
        txt36 = new javax.swing.JTextField();
        txt37 = new javax.swing.JTextField();
        txt38 = new javax.swing.JTextField();
        txt39 = new javax.swing.JTextField();
        txt40 = new javax.swing.JTextField();
        txt41 = new javax.swing.JTextField();
        txt42 = new javax.swing.JTextField();
        txt43 = new javax.swing.JTextField();
        txt44 = new javax.swing.JTextField();
        txt45 = new javax.swing.JTextField();
        txt46 = new javax.swing.JTextField();
        txt47 = new javax.swing.JTextField();
        txt48 = new javax.swing.JTextField();
        txt49 = new javax.swing.JTextField();
        txt50 = new javax.swing.JTextField();
        txt51 = new javax.swing.JTextField();
        txt52 = new javax.swing.JTextField();
        txt53 = new javax.swing.JTextField();
        txt54 = new javax.swing.JTextField();
        txt55 = new javax.swing.JTextField();
        txt56 = new javax.swing.JTextField();
        txt57 = new javax.swing.JTextField();
        txt58 = new javax.swing.JTextField();
        txt59 = new javax.swing.JTextField();
        txt60 = new javax.swing.JTextField();
        txt61 = new javax.swing.JTextField();
        txt62 = new javax.swing.JTextField();
        txt63 = new javax.swing.JTextField();
        txt64 = new javax.swing.JTextField();
        txt65 = new javax.swing.JTextField();
        txt66 = new javax.swing.JTextField();
        txt67 = new javax.swing.JTextField();
        txt68 = new javax.swing.JTextField();
        txt69 = new javax.swing.JTextField();
        txt70 = new javax.swing.JTextField();
        txt71 = new javax.swing.JTextField();
        txt72 = new javax.swing.JTextField();
        txt73 = new javax.swing.JTextField();
        txt74 = new javax.swing.JTextField();
        txt75 = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();
        btnAnterior1 = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt1.setEditable(false);
        txt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt1.setText("1");
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 30, -1));

        txt2.setEditable(false);
        txt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2.setText("2");
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 30, -1));

        txt3.setEditable(false);
        txt3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt3.setText("3");
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 30, 30, -1));

        txt4.setEditable(false);
        txt4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt4.setText("4");
        getContentPane().add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 30, 30, -1));

        txt5.setEditable(false);
        txt5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt5.setText("5");
        getContentPane().add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 30, 30, -1));

        txt6.setEditable(false);
        txt6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt6.setText("6");
        getContentPane().add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 30, 30, -1));

        txt7.setEditable(false);
        txt7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt7.setText("7");
        getContentPane().add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 30, 30, -1));

        txt8.setEditable(false);
        txt8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt8.setText("8");
        getContentPane().add(txt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 30, 30, -1));

        txt9.setEditable(false);
        txt9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt9.setText("9");
        getContentPane().add(txt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 30, 30, -1));

        txt10.setEditable(false);
        txt10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt10.setText("10");
        getContentPane().add(txt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 30, 30, -1));

        txt11.setEditable(false);
        txt11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt11.setText("11");
        getContentPane().add(txt11, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 30, 30, -1));

        txt12.setEditable(false);
        txt12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt12.setText("12");
        getContentPane().add(txt12, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 30, 30, -1));

        txt13.setEditable(false);
        txt13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt13.setText("13");
        getContentPane().add(txt13, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 30, 30, -1));

        txt14.setEditable(false);
        txt14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt14.setText("14");
        getContentPane().add(txt14, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 30, 30, -1));

        txt15.setEditable(false);
        txt15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt15.setText("15");
        getContentPane().add(txt15, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 30, 30, -1));

        txt16.setEditable(false);
        txt16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt16.setText("16");
        getContentPane().add(txt16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 63, 30, -1));

        txt17.setEditable(false);
        txt17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt17.setText("17");
        getContentPane().add(txt17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 63, 30, -1));

        txt18.setEditable(false);
        txt18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt18.setText("18");
        getContentPane().add(txt18, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 63, 30, -1));

        txt19.setEditable(false);
        txt19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt19.setText("19");
        getContentPane().add(txt19, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 63, 30, -1));

        txt20.setEditable(false);
        txt20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt20.setText("20");
        getContentPane().add(txt20, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 63, 30, -1));

        txt21.setEditable(false);
        txt21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt21.setText("21");
        getContentPane().add(txt21, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 63, 30, -1));

        txt22.setEditable(false);
        txt22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt22.setText("22");
        getContentPane().add(txt22, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 63, 30, -1));

        txt23.setEditable(false);
        txt23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt23.setText("23");
        getContentPane().add(txt23, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 63, 30, -1));

        txt24.setEditable(false);
        txt24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt24.setText("24");
        getContentPane().add(txt24, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 63, 30, -1));

        txt25.setEditable(false);
        txt25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt25.setText("25");
        getContentPane().add(txt25, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 63, 30, -1));

        txt26.setEditable(false);
        txt26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt26.setText("26");
        getContentPane().add(txt26, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 63, 30, -1));

        txt27.setEditable(false);
        txt27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt27.setText("27");
        getContentPane().add(txt27, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 63, 30, -1));

        txt28.setEditable(false);
        txt28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt28.setText("28");
        getContentPane().add(txt28, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 63, 30, -1));

        txt29.setEditable(false);
        txt29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt29.setText("29");
        getContentPane().add(txt29, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 63, 30, -1));

        txt30.setEditable(false);
        txt30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt30.setText("30");
        getContentPane().add(txt30, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 63, 30, -1));

        txt31.setEditable(false);
        txt31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt31.setText("31");
        getContentPane().add(txt31, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 96, 30, -1));

        txt32.setEditable(false);
        txt32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt32.setText("32");
        getContentPane().add(txt32, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 96, 30, -1));

        txt33.setEditable(false);
        txt33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt33.setText("33");
        getContentPane().add(txt33, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 96, 30, -1));

        txt34.setEditable(false);
        txt34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt34.setText("34");
        getContentPane().add(txt34, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 96, 30, -1));

        txt35.setEditable(false);
        txt35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt35.setText("35");
        getContentPane().add(txt35, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 96, 30, -1));

        txt36.setEditable(false);
        txt36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt36.setText("36");
        getContentPane().add(txt36, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 96, 30, -1));

        txt37.setEditable(false);
        txt37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt37.setText("37");
        getContentPane().add(txt37, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 96, 30, -1));

        txt38.setEditable(false);
        txt38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt38.setText("38");
        getContentPane().add(txt38, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 96, 30, -1));

        txt39.setEditable(false);
        txt39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt39.setText("39");
        getContentPane().add(txt39, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 96, 30, -1));

        txt40.setEditable(false);
        txt40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt40.setText("40");
        getContentPane().add(txt40, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 96, 30, -1));

        txt41.setEditable(false);
        txt41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt41.setText("41");
        getContentPane().add(txt41, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 96, 30, -1));

        txt42.setEditable(false);
        txt42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt42.setText("42");
        getContentPane().add(txt42, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 96, 30, -1));

        txt43.setEditable(false);
        txt43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt43.setText("43");
        getContentPane().add(txt43, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 96, 30, -1));

        txt44.setEditable(false);
        txt44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt44.setText("44");
        getContentPane().add(txt44, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 96, 30, -1));

        txt45.setEditable(false);
        txt45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt45.setText("45");
        getContentPane().add(txt45, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 96, 30, -1));

        txt46.setEditable(false);
        txt46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt46.setText("46");
        getContentPane().add(txt46, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 129, 30, -1));

        txt47.setEditable(false);
        txt47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt47.setText("47");
        getContentPane().add(txt47, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 129, 30, -1));

        txt48.setEditable(false);
        txt48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt48.setText("48");
        getContentPane().add(txt48, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 129, 30, -1));

        txt49.setEditable(false);
        txt49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt49.setText("49");
        getContentPane().add(txt49, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 129, 30, -1));

        txt50.setEditable(false);
        txt50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt50.setText("50");
        getContentPane().add(txt50, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 129, 30, -1));

        txt51.setEditable(false);
        txt51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt51.setText("51");
        getContentPane().add(txt51, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 129, 30, -1));

        txt52.setEditable(false);
        txt52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt52.setText("52");
        getContentPane().add(txt52, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 129, 30, -1));

        txt53.setEditable(false);
        txt53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt53.setText("53");
        getContentPane().add(txt53, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 129, 30, -1));

        txt54.setEditable(false);
        txt54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt54.setText("54");
        getContentPane().add(txt54, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 129, 30, -1));

        txt55.setEditable(false);
        txt55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt55.setText("55");
        getContentPane().add(txt55, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 129, 30, -1));

        txt56.setEditable(false);
        txt56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt56.setText("56");
        getContentPane().add(txt56, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 129, 30, -1));

        txt57.setEditable(false);
        txt57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt57.setText("57");
        getContentPane().add(txt57, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 129, 30, -1));

        txt58.setEditable(false);
        txt58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt58.setText("58");
        getContentPane().add(txt58, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 129, 30, -1));

        txt59.setEditable(false);
        txt59.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt59.setText("59");
        getContentPane().add(txt59, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 129, 30, -1));

        txt60.setEditable(false);
        txt60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt60.setText("60");
        getContentPane().add(txt60, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 129, 30, -1));

        txt61.setEditable(false);
        txt61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt61.setText("61");
        getContentPane().add(txt61, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 162, 30, -1));

        txt62.setEditable(false);
        txt62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt62.setText("62");
        getContentPane().add(txt62, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 162, 30, -1));

        txt63.setEditable(false);
        txt63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt63.setText("63");
        getContentPane().add(txt63, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 162, 30, -1));

        txt64.setEditable(false);
        txt64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt64.setText("64");
        getContentPane().add(txt64, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 162, 30, -1));

        txt65.setEditable(false);
        txt65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt65.setText("65");
        getContentPane().add(txt65, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 162, 30, -1));

        txt66.setEditable(false);
        txt66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt66.setText("66");
        getContentPane().add(txt66, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 162, 30, -1));

        txt67.setEditable(false);
        txt67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt67.setText("67");
        getContentPane().add(txt67, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 162, 30, -1));

        txt68.setEditable(false);
        txt68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt68.setText("68");
        getContentPane().add(txt68, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 162, 30, -1));

        txt69.setEditable(false);
        txt69.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt69.setText("69");
        getContentPane().add(txt69, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 162, 30, -1));

        txt70.setEditable(false);
        txt70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt70.setText("70");
        getContentPane().add(txt70, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 162, 30, -1));

        txt71.setEditable(false);
        txt71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt71.setText("71");
        getContentPane().add(txt71, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 162, 30, -1));

        txt72.setEditable(false);
        txt72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt72.setText("72");
        getContentPane().add(txt72, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 162, 30, -1));

        txt73.setEditable(false);
        txt73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt73.setText("73");
        getContentPane().add(txt73, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 162, 30, -1));

        txt74.setEditable(false);
        txt74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt74.setText("74");
        getContentPane().add(txt74, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 162, 30, -1));

        txt75.setEditable(false);
        txt75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt75.setText("75");
        getContentPane().add(txt75, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 162, 30, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImgsTablero/FondoTablero.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnAnterior1.setBackground(new java.awt.Color(255, 0, 0));
        btnAnterior1.setForeground(new java.awt.Color(255, 255, 255));
        btnAnterior1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImgsTablero/salir_icon.png"))); // NOI18N
        btnAnterior1.setText("Salir");
        btnAnterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnterior1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnterior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 110, -1));

        btnAnterior.setBackground(new java.awt.Color(255, 0, 0));
        btnAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImgsTablero/anterior_icon.png"))); // NOI18N
        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnterior1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnAnterior1ActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        
    }//GEN-LAST:event_btnAnteriorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnAnterior1;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt13;
    private javax.swing.JTextField txt14;
    private javax.swing.JTextField txt15;
    private javax.swing.JTextField txt16;
    private javax.swing.JTextField txt17;
    private javax.swing.JTextField txt18;
    private javax.swing.JTextField txt19;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt20;
    private javax.swing.JTextField txt21;
    private javax.swing.JTextField txt22;
    private javax.swing.JTextField txt23;
    private javax.swing.JTextField txt24;
    private javax.swing.JTextField txt25;
    private javax.swing.JTextField txt26;
    private javax.swing.JTextField txt27;
    private javax.swing.JTextField txt28;
    private javax.swing.JTextField txt29;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt30;
    private javax.swing.JTextField txt31;
    private javax.swing.JTextField txt32;
    private javax.swing.JTextField txt33;
    private javax.swing.JTextField txt34;
    private javax.swing.JTextField txt35;
    private javax.swing.JTextField txt36;
    private javax.swing.JTextField txt37;
    private javax.swing.JTextField txt38;
    private javax.swing.JTextField txt39;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt40;
    private javax.swing.JTextField txt41;
    private javax.swing.JTextField txt42;
    private javax.swing.JTextField txt43;
    private javax.swing.JTextField txt44;
    private javax.swing.JTextField txt45;
    private javax.swing.JTextField txt46;
    private javax.swing.JTextField txt47;
    private javax.swing.JTextField txt48;
    private javax.swing.JTextField txt49;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt50;
    private javax.swing.JTextField txt51;
    private javax.swing.JTextField txt52;
    private javax.swing.JTextField txt53;
    private javax.swing.JTextField txt54;
    private javax.swing.JTextField txt55;
    private javax.swing.JTextField txt56;
    private javax.swing.JTextField txt57;
    private javax.swing.JTextField txt58;
    private javax.swing.JTextField txt59;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt60;
    private javax.swing.JTextField txt61;
    private javax.swing.JTextField txt62;
    private javax.swing.JTextField txt63;
    private javax.swing.JTextField txt64;
    private javax.swing.JTextField txt65;
    private javax.swing.JTextField txt66;
    private javax.swing.JTextField txt67;
    private javax.swing.JTextField txt68;
    private javax.swing.JTextField txt69;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt70;
    private javax.swing.JTextField txt71;
    private javax.swing.JTextField txt72;
    private javax.swing.JTextField txt73;
    private javax.swing.JTextField txt74;
    private javax.swing.JTextField txt75;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables
}
