/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.JuegoControlador;
import Controlador.TombolaController;
import Modelo.EnumModoJuego;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author ASUS
 */
public class TombolaGUI extends javax.swing.JInternalFrame {

    private static TombolaGUI instancia;
    TableroGUI tablero;
    GUICrearCarton crearcarton;
    /**
     * Creates new form JuegoControladorGUI
     */
    public TombolaGUI() {
        initComponents();
        tablero = TableroGUI.getInstancia();
        crearcarton = GUICrearCarton.getInstancia();
    }
    
    public static TombolaGUI getInstancia() {
    //SINGLETON
        if (instancia == null) {
            instancia = new TombolaGUI();
        }
        return instancia;
    }

    public JToggleButton getBtnAutomatico() {
        return btnAutomatico;
    }

    public JButton getBtnCarton() {
        return btnCarton;
    }

    public JToggleButton getBtnManual() {
        return btnManual;
    }

    public JButton getBtnMarcar() {
        return btnMarcar;
    }

    public JTextField getTxtMostrador() {
        return txtMostrador;
    }

    public JTextField getTxtNumero() {
        return txtNumero;
    }

    public JButton getBtnComenzar() {
        return btnComenzar;
    }

    public JButton getBtnDesmarcar() {
        return btnDesmarcar;
    }
       
    public void reiniciar() {
        btnComenzar.setEnabled(true);
        btnAutomatico.setEnabled(true);
        btnManual.setEnabled(true);
        
        btnMarcar.setEnabled(false);
        btnDesmarcar.setEnabled(false);
        txtNumero.setEnabled(false);
        
        btnJuegoCartonLleno.setEnabled(true);
        btnJuegoCuatroEsquinas.setEnabled(true);
        btnJuegoNormal.setEnabled(true);
    }
    
    public void iniciar() {
    btnComenzar.setEnabled(false);
    }
    
    public void bloquearModoJuego() {
    btnAutomatico.setEnabled(false);
    btnManual.setEnabled(false);
    
        btnJuegoCartonLleno.setEnabled(false);
        btnJuegoCuatroEsquinas.setEnabled(false);
        btnJuegoNormal.setEnabled(false);
    }
    
    public void limpiartxt() {
    txtNumero.setText("");
    }

    public JRadioButton getBtnJuegoCartonLleno() {
        return btnJuegoCartonLleno;
    }

    public JRadioButton getBtnJuegoCuatroEsquinas() {
        return btnJuegoCuatroEsquinas;
    }

    public JRadioButton getBtnJuegoNormal() {
        return btnJuegoNormal;
    }
    
    
    
     /**
     * Actualiza el mostrador con el último número
     * @param numero Número a mostrar (-1 para reset)
     */
    public void actualizarMostrador(int numero) { //AÑADIDO
            if (numero == -1) {
                txtMostrador.setText("00");
            } else { txtMostrador.setText(String.valueOf(numero));
            }
    }
    
     /**
     * Actualiza la interfaz según el modo de juego
     */
    public void actualizarInterfazModo(boolean juegoAutomatico) { //AÑADIDO
            btnMarcar.setEnabled(!juegoAutomatico);
            btnDesmarcar.setEnabled(!juegoAutomatico);
            txtNumero.setEnabled(!juegoAutomatico);           
        }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        btnJuegoNormal = new javax.swing.JRadioButton();
        btnJuegoCuatroEsquinas = new javax.swing.JRadioButton();
        btnJuegoCartonLleno = new javax.swing.JRadioButton();
        txtNumero = new javax.swing.JTextField();
        txtMostrador = new javax.swing.JTextField();
        btnMarcar = new javax.swing.JButton();
        btnDesmarcar = new javax.swing.JButton();
        btnComenzar = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        btnCarton = new javax.swing.JButton();
        btnTablero = new javax.swing.JButton();
        btnAutomatico = new javax.swing.JToggleButton();
        btnManual = new javax.swing.JToggleButton();
        txt = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJuegoNormal.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup2.add(btnJuegoNormal);
        btnJuegoNormal.setForeground(new java.awt.Color(255, 255, 255));
        btnJuegoNormal.setSelected(true);
        btnJuegoNormal.setText("Normal");
        btnJuegoNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegoNormalActionPerformed(evt);
            }
        });
        getContentPane().add(btnJuegoNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 178, -1, -1));

        buttonGroup2.add(btnJuegoCuatroEsquinas);
        btnJuegoCuatroEsquinas.setForeground(new java.awt.Color(255, 255, 255));
        btnJuegoCuatroEsquinas.setText("Cuatro Esquinas");
        btnJuegoCuatroEsquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegoCuatroEsquinasActionPerformed(evt);
            }
        });
        getContentPane().add(btnJuegoCuatroEsquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 198, -1, -1));

        buttonGroup2.add(btnJuegoCartonLleno);
        btnJuegoCartonLleno.setForeground(new java.awt.Color(255, 255, 255));
        btnJuegoCartonLleno.setText("Carton Lleno");
        btnJuegoCartonLleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegoCartonLlenoActionPerformed(evt);
            }
        });
        getContentPane().add(btnJuegoCartonLleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 218, -1, -1));
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 60, -1));

        txtMostrador.setBackground(new java.awt.Color(0, 0, 0));
        txtMostrador.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        txtMostrador.setForeground(new java.awt.Color(255, 255, 255));
        txtMostrador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMostrador.setText("00");
        txtMostrador.setBorder(null);
        getContentPane().add(txtMostrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 30, -1, -1));

        btnMarcar.setText("Marcar ");
        btnMarcar.setEnabled(false);
        btnMarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMarcar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 110, -1));

        btnDesmarcar.setText("Desmarcar ");
        btnDesmarcar.setEnabled(false);
        btnDesmarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesmarcarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDesmarcar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 110, -1));

        btnComenzar.setBackground(new java.awt.Color(255, 0, 0));
        btnComenzar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImgsMenuPrincipal/Comenzar.png"))); // NOI18N
        btnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 30, 30));

        btnReiniciar.setBackground(new java.awt.Color(255, 0, 0));
        btnReiniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImgsMenuPrincipal/reiniciar_icon.png"))); // NOI18N
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 30, 30));

        btnCarton.setBackground(new java.awt.Color(255, 0, 0));
        btnCarton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCarton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImgsMenuPrincipal/agregar_icon.png"))); // NOI18N
        btnCarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartonActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 30, 30));

        btnTablero.setBackground(new java.awt.Color(255, 0, 0));
        btnTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImgsMenuPrincipal/tabla_icon.png"))); // NOI18N
        btnTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableroActionPerformed(evt);
            }
        });
        getContentPane().add(btnTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 30, 30));

        buttonGroup1.add(btnAutomatico);
        btnAutomatico.setText("Automatico");
        btnAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomaticoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 178, 160, -1));

        buttonGroup1.add(btnManual);
        btnManual.setSelected(true);
        btnManual.setText("Manual");
        btnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualActionPerformed(evt);
            }
        });
        getContentPane().add(btnManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 208, 160, -1));

        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setText("Modos de juego:");
        getContentPane().add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 160, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImgsMenuPrincipal/FondoMenu.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartonActionPerformed
        JuegoControlador.getInstancia().agregarCarton();
    }//GEN-LAST:event_btnCartonActionPerformed

    private void btnTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableroActionPerformed
        tablero.setVisible(true);
    }//GEN-LAST:event_btnTableroActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        JuegoControlador.getInstancia().reiniciarJuego();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarActionPerformed
        try {   
            JuegoControlador.getInstancia().IniciarJuego();
        } catch (InterruptedException ex) {
            Logger.getLogger(TombolaGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnComenzarActionPerformed

    private void btnAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomaticoActionPerformed
        JuegoControlador.getInstancia().setJuegoAutomatico(true);
    }//GEN-LAST:event_btnAutomaticoActionPerformed

    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed
        JuegoControlador.getInstancia().setJuegoAutomatico(false);
    }//GEN-LAST:event_btnManualActionPerformed

    private void btnMarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarActionPerformed
    String textoNumero = txtNumero.getText().trim();
    if (textoNumero.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe ingresar un número para marcar.", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
        return; 
    }
    int numero;
    try { 
        numero = Integer.parseInt(textoNumero);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El valor ingresado no es un número válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        return; 
    }
    if (numero < 1 || numero > 75) {
        JOptionPane.showMessageDialog(this, "El número debe estar entre 1 y 75.", "Error de Rango", JOptionPane.ERROR_MESSAGE);
        return;
    }
    JuegoControlador.getInstancia().marcarNumero(numero);
    txtNumero.setText("");  

// JuegoControlador.getInstancia().procesarNumero(Integer.parseInt(txtNumero.getText().trim()));
    }//GEN-LAST:event_btnMarcarActionPerformed

    private void btnDesmarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesmarcarActionPerformed
    String textoNumero = txtNumero.getText().trim();
    if (textoNumero.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe ingresar un número para marcar.", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
        return; 
    }
    int numero;
    try { 
        numero = Integer.parseInt(textoNumero);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El valor ingresado no es un número válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        return; 
    }
    if (numero < 1 || numero > 75) {
        JOptionPane.showMessageDialog(this, "El número debe estar entre 1 y 75.", "Error de Rango", JOptionPane.ERROR_MESSAGE);
        return;
    }
    JuegoControlador.getInstancia().marcarNumero(numero);
    txtNumero.setText("");  
    }//GEN-LAST:event_btnDesmarcarActionPerformed

    private void btnJuegoCuatroEsquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegoCuatroEsquinasActionPerformed
            if (btnJuegoCuatroEsquinas.isSelected()) {
                JuegoControlador.getInstancia().setModoJuego(EnumModoJuego.CUATRO_ESQUINAS);
            }
    }//GEN-LAST:event_btnJuegoCuatroEsquinasActionPerformed

    private void btnJuegoNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegoNormalActionPerformed
            if (btnJuegoNormal.isSelected()) {
                JuegoControlador.getInstancia().setModoJuego(EnumModoJuego.NORMAL);
            }
    }//GEN-LAST:event_btnJuegoNormalActionPerformed

    private void btnJuegoCartonLlenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegoCartonLlenoActionPerformed
            if (btnJuegoCartonLleno.isSelected()) {
                JuegoControlador.getInstancia().setModoJuego(EnumModoJuego.CARTON_LLENO);
            }
    }//GEN-LAST:event_btnJuegoCartonLlenoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JToggleButton btnAutomatico;
    private javax.swing.JButton btnCarton;
    private javax.swing.JButton btnComenzar;
    private javax.swing.JButton btnDesmarcar;
    private javax.swing.JRadioButton btnJuegoCartonLleno;
    private javax.swing.JRadioButton btnJuegoCuatroEsquinas;
    private javax.swing.JRadioButton btnJuegoNormal;
    private javax.swing.JToggleButton btnManual;
    private javax.swing.JButton btnMarcar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnTablero;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel txt;
    private javax.swing.JTextField txtMostrador;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
