/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.JuegoControlador;
import Controlador.TombolaController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author ASUS
 */
public class TombolaGUI extends javax.swing.JInternalFrame {

    private static TombolaGUI instancia;
    TableroGUI tablero;
    /**
     * Creates new form JuegoControladorGUI
     */
    public TombolaGUI() {
        initComponents();
        tablero = TableroGUI.getInstancia();
    }
    
    public static TombolaGUI getInstancia() {
    //SINGLETON
        if (instancia == null) {
            instancia = new TombolaGUI();
        }
        return instancia;
    }

    public JToggleButton getBtnAutomatico() {
        return btnAutomatico;
    }

    public JButton getBtnCarton() {
        return btnCarton;
    }

    public JToggleButton getBtnManual() {
        return btnManual;
    }

    public JButton getBtnMarcar() {
        return btnMarcar;
    }

    public JTextField getTxtMostrador() {
        return txtMostrador;
    }

    public JFormattedTextField getTxtNumero() {
        return txtNumero;
    }

    public JButton getBtnComenzar() {
        return btnComenzar;
    }

    public JButton getBtnDesmarcar() {
        return btnDesmarcar;
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtMostrador = new javax.swing.JTextField();
        txtNumero = new javax.swing.JFormattedTextField();
        btnMarcar = new javax.swing.JButton();
        btnDesmarcar = new javax.swing.JButton();
        btnComenzar = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        btnCarton = new javax.swing.JButton();
        btnTablero = new javax.swing.JButton();
        btnAutomatico = new javax.swing.JToggleButton();
        btnManual = new javax.swing.JToggleButton();
        txt = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMostrador.setBackground(new java.awt.Color(0, 0, 0));
        txtMostrador.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        txtMostrador.setForeground(new java.awt.Color(255, 255, 255));
        txtMostrador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMostrador.setText("00");
        txtMostrador.setBorder(null);
        getContentPane().add(txtMostrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 30, -1, -1));

        try {
            txtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero.setEnabled(false);
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 60, -1));

        btnMarcar.setText("Marcar ");
        btnMarcar.setEnabled(false);
        btnMarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMarcar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 110, -1));

        btnDesmarcar.setText("Desmarcar ");
        btnDesmarcar.setEnabled(false);
        btnDesmarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesmarcarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDesmarcar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 110, -1));

        btnComenzar.setBackground(new java.awt.Color(255, 0, 0));
        btnComenzar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImgsMenuPrincipal/Comenzar.png"))); // NOI18N
        btnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 30, 30));

        btnReiniciar.setBackground(new java.awt.Color(255, 0, 0));
        btnReiniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImgsMenuPrincipal/reiniciar_icon.png"))); // NOI18N
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 30, 30));

        btnCarton.setBackground(new java.awt.Color(255, 0, 0));
        btnCarton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCarton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImgsMenuPrincipal/agregar_icon.png"))); // NOI18N
        btnCarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartonActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 30, 30));

        btnTablero.setBackground(new java.awt.Color(255, 0, 0));
        btnTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImgsMenuPrincipal/tabla_icon.png"))); // NOI18N
        btnTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableroActionPerformed(evt);
            }
        });
        getContentPane().add(btnTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 30, 30));

        buttonGroup1.add(btnAutomatico);
        btnAutomatico.setText("Automatico");
        btnAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomaticoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 280, -1));

        buttonGroup1.add(btnManual);
        btnManual.setSelected(true);
        btnManual.setText("Manual");
        btnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualActionPerformed(evt);
            }
        });
        getContentPane().add(btnManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 280, -1));

        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setText("Modos de juego:");
        getContentPane().add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 160, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ImgsMenuPrincipal/FondoMenu.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartonActionPerformed
        
    }//GEN-LAST:event_btnCartonActionPerformed

    private void btnTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableroActionPerformed
        tablero.setVisible(true);
    }//GEN-LAST:event_btnTableroActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        JuegoControlador.getInstancia().reiniciarJuego();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarActionPerformed
        try {   
            JuegoControlador.getInstancia().IniciarJuego();
        } catch (InterruptedException ex) {
            Logger.getLogger(TombolaGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnComenzarActionPerformed

    private void btnAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomaticoActionPerformed
        JuegoControlador.getInstancia().setJuegoAutomatico(true);
    }//GEN-LAST:event_btnAutomaticoActionPerformed

    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed
        JuegoControlador.getInstancia().setJuegoAutomatico(false);
    }//GEN-LAST:event_btnManualActionPerformed

    private void btnMarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarActionPerformed
        int numero = Integer.parseInt(txtNumero.getText().trim());
        JuegoControlador.getInstancia().marcarNumero(numero);

// JuegoControlador.getInstancia().procesarNumero(Integer.parseInt(txtNumero.getText().trim()));
    }//GEN-LAST:event_btnMarcarActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        int numero = Integer.parseInt(txtNumero.getText().trim());
        JuegoControlador.getInstancia().marcarNumero(numero);

//JuegoControlador.getInstancia().marcarNumero(Integer.parseInt(txtNumero.getText().trim()));
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void btnDesmarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesmarcarActionPerformed
       int numero = Integer.parseInt(txtNumero.getText().trim());
        JuegoControlador.getInstancia().desmarcarNumero(numero);
    }//GEN-LAST:event_btnDesmarcarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JToggleButton btnAutomatico;
    private javax.swing.JButton btnCarton;
    private javax.swing.JButton btnComenzar;
    private javax.swing.JButton btnDesmarcar;
    private javax.swing.JToggleButton btnManual;
    private javax.swing.JButton btnMarcar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnTablero;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel txt;
    private javax.swing.JTextField txtMostrador;
    private javax.swing.JFormattedTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
